### ISSUE TITLE
Deployment verification

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/greenfield-template#333]
Create smoke tests or some other fast way to check if a deployment was successful.  Should do more than a simple OpenShift readiness probe.  Then use it to confirm TEST and PROD deployments instead of ZAP.

Previous title: Smoke/Light tests

**Comment by gormless87** [comment]
Put verification in  GFT after FOM

**Comment by gormless87** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FSA-Fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/greenfield-template/333?planning-poker) with ZenHub @DerekRoberts @ConradBoydElliottGustafson @franTarkenton @explorertolu
