### ISSUE TITLE
Dark deployments (night)

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/greenfield-template#407]
Deployment integration happens any time, but deployments happen during off hours, like 4 AM.

This will provide ability to deploy without a downtime of apps. 

Could be useful for FOM demo environment. (Need to discuss when deployments will be pushed to demo -at Production or after Test?)

**Comment by gormless87** [comment]
Team discussion lead to a number of questions as to why this ability is required - business case

More investigation required.

**Comment by ArogeG** [comment]
Team decided that this isn't needed.
